export const templates = [
  // MARKETING DIGITAL (100 prompts)
  { id: 1, category: "marketing", title: "Headline para Anúncio", prompt: "Crie 5 headlines persuasivas para um anúncio de Facebook sobre [produto/serviço] que desperte curiosidade e urgência." },
  { id: 2, category: "marketing", title: "Estratégia de Lançamento", prompt: "Desenvolva uma estratégia completa de lançamento de 7 dias para [produto] incluindo emails, posts e stories." },
  { id: 3, category: "marketing", title: "Funil de Vendas", prompt: "Crie um funil de vendas completo para [produto] com 5 etapas: atração, captura, nutrição, venda e pós-venda." },
  { id: 4, category: "marketing", title: "Copy para Landing Page", prompt: "Escreva uma copy completa para landing page de [produto] usando a fórmula AIDA (Atenção, Interesse, Desejo, Ação)." },
  { id: 5, category: "marketing", title: "Sequência de Emails", prompt: "Crie uma sequência de 7 emails de vendas para [produto] seguindo a jornada do cliente." },
  { id: 6, category: "marketing", title: "Anúncio para Instagram", prompt: "Escreva 3 variações de copy para anúncio no Instagram sobre [produto] com CTA forte." },
  { id: 7, category: "marketing", title: "Script de Vídeo de Vendas", prompt: "Crie um roteiro de vídeo de 60 segundos para vender [produto] no Reels/TikTok." },
  { id: 8, category: "marketing", title: "Oferta Irresistível", prompt: "Transforme [produto] em uma oferta irresistível com bônus, garantia e escassez." },
  { id: 9, category: "marketing", title: "Bio do Instagram", prompt: "Escreva uma bio magnética para Instagram de afiliado que vende [nicho/produto]." },
  { id: 10, category: "marketing", title: "Post Viral", prompt: "Crie um post viral sobre [tema] que gere engajamento e leve pessoas ao link na bio." },
  { id: 11, category: "marketing", title: "Estratégia de Conteúdo", prompt: "Desenvolva um calendário de conteúdo de 30 dias para Instagram sobre [nicho]." },
  { id: 12, category: "marketing", title: "Pitch de Vendas", prompt: "Crie um pitch de vendas de 30 segundos para [produto] que funcione em stories e vídeos." },
  { id: 13, category: "marketing", title: "Email de Boas-vindas", prompt: "Escreva um email de boas-vindas para novos leads de [produto] que gere conexão imediata." },
  { id: 14, category: "marketing", title: "Anúncio para YouTube", prompt: "Crie um script de anúncio de 15 segundos para YouTube sobre [produto]." },
  { id: 15, category: "marketing", title: "Estratégia de Remarketing", prompt: "Desenvolva uma estratégia de remarketing para recuperar vendas perdidas de [produto]." },
  { id: 16, category: "marketing", title: "Copy para WhatsApp", prompt: "Escreva 5 mensagens de vendas para WhatsApp sobre [produto] que não pareçam spam." },
  { id: 17, category: "marketing", title: "Post de Depoimento", prompt: "Crie um post de depoimento fictício (baseado em resultados reais) para [produto]." },
  { id: 18, category: "marketing", title: "Estratégia de Upsell", prompt: "Desenvolva uma estratégia de upsell para aumentar o ticket médio de [produto]." },
  { id: 19, category: "marketing", title: "Copy para Pinterest", prompt: "Escreva 5 descrições otimizadas para pins do Pinterest sobre [produto/nicho]." },
  { id: 20, category: "marketing", title: "Anúncio para TikTok", prompt: "Crie um script de anúncio nativo para TikTok sobre [produto] que pareça conteúdo orgânico." },
  { id: 21, category: "marketing", title: "Sequência de Stories", prompt: "Crie uma sequência de 10 stories vendendo [produto] com gatilhos mentais." },
  { id: 22, category: "marketing", title: "Email de Recuperação", prompt: "Escreva um email para recuperar carrinho abandonado de [produto] com urgência." },
  { id: 23, category: "marketing", title: "Post Educativo", prompt: "Crie um post educativo sobre [tema] que naturalmente leve à venda de [produto]." },
  { id: 24, category: "marketing", title: "Estratégia de Cross-sell", prompt: "Desenvolva uma estratégia de cross-sell para vender [produto complementar] para clientes de [produto principal]." },
  { id: 25, category: "marketing", title: "Copy para Telegram", prompt: "Escreva uma mensagem de vendas para grupo do Telegram sobre [produto]." },
  { id: 26, category: "marketing", title: "Anúncio para LinkedIn", prompt: "Crie um post patrocinado para LinkedIn sobre [produto B2B/serviço]." },
  { id: 27, category: "marketing", title: "Post de Autoridade", prompt: "Escreva um post que posicione você como autoridade em [nicho] e venda [produto]." },
  { id: 28, category: "marketing", title: "Estratégia de Lançamento Semente", prompt: "Desenvolva uma estratégia de lançamento semente para validar [produto] antes do lançamento oficial." },
  { id: 29, category: "marketing", title: "Copy para Facebook Groups", prompt: "Escreva um post para grupos do Facebook sobre [produto] que não seja banido." },
  { id: 30, category: "marketing", title: "Sequência de Onboarding", prompt: "Crie uma sequência de 5 emails de onboarding para novos clientes de [produto]." },
  { id: 31, category: "marketing", title: "Post de Bastidores", prompt: "Crie um post mostrando bastidores do seu negócio que gere curiosidade sobre [produto]." },
  { id: 32, category: "marketing", title: "Estratégia de Afiliados", prompt: "Desenvolva uma estratégia completa para vender como afiliado de [produto]." },
  { id: 33, category: "marketing", title: "Copy para Quora", prompt: "Escreva uma resposta no Quora sobre [pergunta] que naturalmente mencione [produto]." },
  { id: 34, category: "marketing", title: "Anúncio para Twitter/X", prompt: "Crie uma thread de vendas no Twitter/X sobre [produto] com 5 tweets." },
  { id: 35, category: "marketing", title: "Post de Prova Social", prompt: "Escreva um post destacando resultados de clientes de [produto] de forma autêntica." },
  { id: 36, category: "marketing", title: "Estratégia de Webinar", prompt: "Desenvolva uma estratégia completa de webinar para vender [produto]." },
  { id: 37, category: "marketing", title: "Copy para Descrição de Produto", prompt: "Escreva uma descrição persuasiva para página de vendas de [produto]." },
  { id: 38, category: "marketing", title: "Post de Pergunta", prompt: "Crie um post com pergunta que gere engajamento e leve naturalmente a [produto]." },
  { id: 39, category: "marketing", title: "Estratégia de Email Marketing", prompt: "Desenvolva uma estratégia de email marketing de 90 dias para [produto]." },
  { id: 40, category: "marketing", title: "Copy para Checkout", prompt: "Escreva textos persuasivos para página de checkout de [produto] que reduzam abandono." },
  { id: 41, category: "marketing", title: "Post de Mito vs Verdade", prompt: "Crie um post desmistificando [mito do nicho] e apresentando [produto] como solução." },
  { id: 42, category: "marketing", title: "Estratégia de Parcerias", prompt: "Desenvolva uma estratégia de parcerias com influenciadores para promover [produto]." },
  { id: 43, category: "marketing", title: "Copy para Popup", prompt: "Escreva textos para popup de captura de leads sobre [produto/isca digital]." },
  { id: 44, category: "marketing", title: "Post de Lista", prompt: "Crie um post no formato 'X coisas que...' sobre [tema] que mencione [produto]." },
  { id: 45, category: "marketing", title: "Estratégia de SEO", prompt: "Desenvolva uma estratégia de SEO para rankear [palavra-chave] relacionada a [produto]." },
  { id: 46, category: "marketing", title: "Copy para Banner", prompt: "Escreva textos curtos e impactantes para banners de [produto]." },
  { id: 47, category: "marketing", title: "Post de Transformação", prompt: "Crie um post mostrando transformação antes/depois usando [produto]." },
  { id: 48, category: "marketing", title: "Estratégia de Conteúdo Evergreen", prompt: "Desenvolva 10 ideias de conteúdo evergreen para [nicho] que continuem vendendo." },
  { id: 49, category: "marketing", title: "Copy para Notificação Push", prompt: "Escreva 5 notificações push para recuperar clientes de [produto]." },
  { id: 50, category: "marketing", title: "Post de Enquete", prompt: "Crie uma enquete para stories que gere engajamento e venda [produto]." },
  { id: 51, category: "marketing", title: "Estratégia de Black Friday", prompt: "Desenvolva uma estratégia completa de Black Friday para [produto]." },
  { id: 52, category: "marketing", title: "Copy para Testimonial", prompt: "Escreva um roteiro para pedir depoimentos em vídeo de clientes de [produto]." },
  { id: 53, category: "marketing", title: "Post de Controvérsia", prompt: "Crie um post polêmico (mas respeitoso) sobre [tema] que gere debate e mencione [produto]." },
  { id: 54, category: "marketing", title: "Estratégia de Pré-lançamento", prompt: "Desenvolva uma estratégia de pré-lançamento de 30 dias para [produto]." },
  { id: 55, category: "marketing", title: "Copy para SMS", prompt: "Escreva 5 mensagens SMS curtas para promover [produto/oferta]." },
  { id: 56, category: "marketing", title: "Post de Tutorial", prompt: "Crie um post tutorial sobre [tema] que naturalmente leve a [produto]." },
  { id: 57, category: "marketing", title: "Estratégia de Retargeting", prompt: "Desenvolva uma estratégia de retargeting multi-plataforma para [produto]." },
  { id: 58, category: "marketing", title: "Copy para Bio Link", prompt: "Escreva textos para página de bio link (Linktree) sobre [produto]." },
  { id: 59, category: "marketing", title: "Post de Storytelling", prompt: "Crie um post contando uma história pessoal que conecte com [produto]." },
  { id: 60, category: "marketing", title: "Estratégia de Lançamento Interno", prompt: "Desenvolva uma estratégia de lançamento interno (carrinho aberto) para [produto]." },
  { id: 61, category: "marketing", title: "Copy para Anúncio Nativo", prompt: "Escreva um anúncio nativo que pareça artigo de blog sobre [produto]." },
  { id: 62, category: "marketing", title: "Post de Comparação", prompt: "Crie um post comparando [produto] com alternativas do mercado de forma justa." },
  { id: 63, category: "marketing", title: "Estratégia de Growth Hacking", prompt: "Desenvolva 5 estratégias de growth hacking para [produto]." },
  { id: 64, category: "marketing", title: "Copy para Landing Page Mobile", prompt: "Escreva copy otimizada para landing page mobile de [produto]." },
  { id: 65, category: "marketing", title: "Post de Curiosidade", prompt: "Crie um post com curiosidade sobre [nicho] que leve a [produto]." },
  { id: 66, category: "marketing", title: "Estratégia de Automação", prompt: "Desenvolva uma estratégia de automação de marketing para [produto]." },
  { id: 67, category: "marketing", title: "Copy para Checkout Upsell", prompt: "Escreva copy para página de upsell após compra de [produto]." },
  { id: 68, category: "marketing", title: "Post de Desafio", prompt: "Crie um post de desafio (30 dias, 7 dias) relacionado a [nicho/produto]." },
  { id: 69, category: "marketing", title: "Estratégia de Comunidade", prompt: "Desenvolva uma estratégia para criar comunidade em torno de [produto/nicho]." },
  { id: 70, category: "marketing", title: "Copy para Thank You Page", prompt: "Escreva copy para página de obrigado após compra de [produto]." },
  { id: 71, category: "marketing", title: "Post de FAQ", prompt: "Crie um post respondendo perguntas frequentes sobre [produto/nicho]." },
  { id: 72, category: "marketing", title: "Estratégia de Influencer Marketing", prompt: "Desenvolva uma estratégia de marketing de influência para [produto]." },
  { id: 73, category: "marketing", title: "Copy para Order Bump", prompt: "Escreva copy para order bump (oferta adicional no checkout) de [produto]." },
  { id: 74, category: "marketing", title: "Post de Infográfico", prompt: "Crie um post no formato infográfico sobre [tema] que mencione [produto]." },
  { id: 75, category: "marketing", title: "Estratégia de Conteúdo UGC", prompt: "Desenvolva uma estratégia para gerar conteúdo UGC (User Generated Content) sobre [produto]." },
  { id: 76, category: "marketing", title: "Copy para Abandoned Cart", prompt: "Escreva sequência de 3 emails para carrinho abandonado de [produto]." },
  { id: 77, category: "marketing", title: "Post de Checklist", prompt: "Crie um post com checklist sobre [tema] que leve a [produto]." },
  { id: 78, category: "marketing", title: "Estratégia de Lançamento perpétuo", prompt: "Desenvolva uma estratégia de lançamento perpétuo (carrinho sempre aberto) para [produto]." },
  { id: 79, category: "marketing", title: "Copy para Social Proof", prompt: "Escreva textos para destacar prova social (depoimentos, números) de [produto]." },
  { id: 80, category: "marketing", title: "Post de Before/After", prompt: "Crie um post mostrando antes/depois de usar [produto/método]." },
  { id: 81, category: "marketing", title: "Estratégia de Affiliate Launch", prompt: "Desenvolva uma estratégia de lançamento com afiliados para [produto]." },
  { id: 82, category: "marketing", title: "Copy para Guarantee", prompt: "Escreva copy para seção de garantia de [produto] que aumente conversões." },
  { id: 83, category: "marketing", title: "Post de Quote", prompt: "Crie um post com citação inspiracional relacionada a [nicho/produto]." },
  { id: 84, category: "marketing", title: "Estratégia de Product Launch Formula", prompt: "Desenvolva uma estratégia baseada em Product Launch Formula para [produto]." },
  { id: 85, category: "marketing", title: "Copy para Scarcity", prompt: "Escreva textos de escassez para [produto] que sejam críveis e eficazes." },
  { id: 86, category: "marketing", title: "Post de Case Study", prompt: "Crie um post de estudo de caso sobre cliente que teve resultados com [produto]." },
  { id: 87, category: "marketing", title: "Estratégia de Joint Venture", prompt: "Desenvolva uma estratégia de joint venture para lançar [produto]." },
  { id: 88, category: "marketing", title: "Copy para Urgency", prompt: "Escreva textos de urgência para [produto] que gerem ação imediata." },
  { id: 89, category: "marketing", title: "Post de Behind the Scenes", prompt: "Crie um post mostrando bastidores da criação de [produto]." },
  { id: 90, category: "marketing", title: "Estratégia de Membership", prompt: "Desenvolva uma estratégia de membership/assinatura para [nicho]." },
  { id: 91, category: "marketing", title: "Copy para Bonus", prompt: "Escreva descrições persuasivas para bônus de [produto]." },
  { id: 92, category: "marketing", title: "Post de Milestone", prompt: "Crie um post celebrando marco (1000 alunos, 1 ano, etc) de [produto]." },
  { id: 93, category: "marketing", title: "Estratégia de High Ticket", prompt: "Desenvolva uma estratégia para vender produto high ticket (acima de R$ 2000)." },
  { id: 94, category: "marketing", title: "Copy for Pricing", prompt: "Escreva copy para seção de preços de [produto] que justifique o valor." },
  { id: 95, category: "marketing", title: "Post de Announcement", prompt: "Crie um post anunciando novidade/atualização de [produto]." },
  { id: 96, category: "marketing", title: "Estratégia de Tripwire", prompt: "Desenvolva uma estratégia de tripwire (produto de entrada barato) para [nicho]." },
  { id: 97, category: "marketing", title: "Copy for Features", prompt: "Escreva descrições de features/benefícios de [produto] focadas em transformação." },
  { id: 98, category: "marketing", title: "Post de Teaser", prompt: "Crie um post de teaser/anticipação para lançamento de [produto]." },
  { id: 99, category: "marketing", title: "Estratégia de Funnel", prompt: "Desenvolva um funil de vendas completo (topo, meio, fundo) para [produto]." },
  { id: 100, category: "marketing", title: "Copy for CTA", prompt: "Escreva 10 variações de CTA (Call to Action) para [produto/oferta]." },

  // COPYWRITING (100 prompts)
  { id: 101, category: "copywriting", title: "Headline com Número", prompt: "Crie 10 headlines usando números específicos sobre [tema] que gerem curiosidade." },
  { id: 102, category: "copywriting", title: "Headline com 'Como'", prompt: "Escreva 10 headlines no formato 'Como [resultado] sem [objeção]' sobre [tema]." },
  { id: 103, category: "copywriting", title: "Headline com Pergunta", prompt: "Crie 10 headlines com perguntas provocativas sobre [tema/produto]." },
  { id: 104, category: "copywriting", title: "Headline com Urgência", prompt: "Escreva 10 headlines que criem senso de urgência sobre [oferta/produto]." },
  { id: 105, category: "copywriting", title: "Headline com Curiosidade", prompt: "Crie 10 headlines que despertem curiosidade extrema sobre [tema]." },
  { id: 106, category: "copywriting", title: "Subheadline Complementar", prompt: "Escreva 5 subheadlines que complementem e fortaleçam a headline principal sobre [tema]." },
  { id: 107, category: "copywriting", title: "Bullet Points Persuasivos", prompt: "Crie 15 bullet points persuasivos destacando benefícios de [produto]." },
  { id: 108, category: "copywriting", title: "Parágrafo de Abertura", prompt: "Escreva um parágrafo de abertura magnético para copy de vendas sobre [produto]." },
  { id: 109, category: "copywriting", title: "Storytelling de Vendas", prompt: "Crie uma história de 300 palavras que venda [produto] de forma indireta." },
  { id: 110, category: "copywriting", title: "Gatilho de Escassez", prompt: "Escreva 5 parágrafos usando gatilho de escassez para [produto/oferta]." },
  { id: 111, category: "copywriting", title: "Gatilho de Urgência", prompt: "Crie 5 parágrafos usando gatilho de urgência para [produto/oferta]." },
  { id: 112, category: "copywriting", title: "Gatilho de Autoridade", prompt: "Escreva 5 parágrafos usando gatilho de autoridade para [produto/marca]." },
  { id: 113, category: "copywriting", title: "Gatilho de Prova Social", prompt: "Crie 5 parágrafos usando gatilho de prova social para [produto]." },
  { id: 114, category: "copywriting", title: "Gatilho de Reciprocidade", prompt: "Escreva 5 parágrafos usando gatilho de reciprocidade para [produto/oferta]." },
  { id: 115, category: "copywriting", title: "Gatilho de Compromisso", prompt: "Crie 5 parágrafos usando gatilho de compromisso e coerência para [produto]." },
  { id: 116, category: "copywriting", title: "Gatilho de Afeição", prompt: "Escreva 5 parágrafos usando gatilho de afeição/likability para [produto]." },
  { id: 117, category: "copywriting", title: "Gatilho de Inimigo Comum", prompt: "Crie 5 parágrafos usando gatilho de inimigo comum para [produto/nicho]." },
  { id: 118, category: "copywriting", title: "Gatilho de Novidade", prompt: "Escreva 5 parágrafos usando gatilho de novidade para [produto/lançamento]." },
  { id: 119, category: "copywriting", title: "CTA Forte", prompt: "Crie 10 CTAs (Call to Action) irresistíveis para [produto/oferta]." },
  { id: 120, category: "copywriting", title: "CTA com Benefício", prompt: "Escreva 10 CTAs que destaquem o benefício principal de [produto]." },
  { id: 121, category: "copywriting", title: "CTA com Urgência", prompt: "Crie 10 CTAs que criem senso de urgência para [oferta]." },
  { id: 122, category: "copywriting", title: "CTA com Curiosidade", prompt: "Escreva 10 CTAs que despertem curiosidade sobre [produto/conteúdo]." },
  { id: 123, category: "copywriting", title: "CTA com Exclusividade", prompt: "Crie 10 CTAs que transmitam exclusividade para [oferta/produto]." },
  { id: 124, category: "copywriting", title: "Parágrafo de Transição", prompt: "Escreva 5 parágrafos de transição suaves entre seções de copy sobre [tema]." },
  { id: 125, category: "copywriting", title: "Seção de Objeções", prompt: "Crie uma seção completa respondendo as 5 principais objeções para comprar [produto]." },
  { id: 126, category: "copywriting", title: "Seção de Garantia", prompt: "Escreva uma seção de garantia poderosa para [produto] que elimine riscos." },
  { id: 127, category: "copywriting", title: "Seção de Bônus", prompt: "Crie descrições persuasivas para 5 bônus de [produto]." },
  { id: 128, category: "copywriting", title: "Seção de Depoimentos", prompt: "Escreva uma introdução para seção de depoimentos de [produto] que gere credibilidade." },
  { id: 129, category: "copywriting", title: "Seção 'Para Quem É'", prompt: "Crie uma seção 'Para quem é este produto' para [produto] que qualifique o público." },
  { id: 130, category: "copywriting", title: "Seção 'Para Quem Não É'", prompt: "Escreva uma seção 'Para quem NÃO é este produto' para [produto] que gere exclusividade." },
  { id: 131, category: "copywriting", title: "Seção de Preços", prompt: "Crie uma seção de preços ancorada para [produto] que justifique o valor." },
  { id: 132, category: "copywriting", title: "Seção 'O Que Você Vai Receber'", prompt: "Escreva uma seção detalhada do que o cliente recebe ao comprar [produto]." },
  { id: 133, category: "copywriting", title: "Seção de FAQ", prompt: "Crie 10 perguntas frequentes com respostas persuasivas para [produto]." },
  { id: 134, category: "copywriting", title: "Seção de Sobre o Criador", prompt: "Escreva uma seção 'Sobre o Criador' para [produto] que gere conexão e autoridade." },
  { id: 135, category: "copywriting", title: "Seção de Metodologia", prompt: "Crie uma seção explicando a metodologia por trás de [produto/método]." },
  { id: 136, category: "copywriting", title: "Seção de Resultados", prompt: "Escreva uma seção destacando resultados esperados com [produto] de forma realista." },
  { id: 137, category: "copywriting", title: "Seção de Diferenciais", prompt: "Crie uma seção destacando os diferenciais únicos de [produto] vs concorrência." },
  { id: 138, category: "copywriting", title: "Seção de Transformação", prompt: "Escreva uma seção mostrando a transformação do ponto A ao ponto B com [produto]." },
  { id: 139, category: "copywriting", title: "Seção de Dor/Problema", prompt: "Crie uma seção agitando a dor/problema que [produto] resolve." },
  { id: 140, category: "copywriting", title: "Seção de Solução", prompt: "Escreva uma seção apresentando [produto] como a solução definitiva para [problema]." },
  { id: 141, category: "copywriting", title: "Email de Vendas - Abertura", prompt: "Escreva 5 aberturas de email de vendas que prendam a atenção nos primeiros 3 segundos." },
  { id: 142, category: "copywriting", title: "Email de Vendas - Corpo", prompt: "Crie o corpo de um email de vendas de 400 palavras para [produto]." },
  { id: 143, category: "copywriting", title: "Email de Vendas - Fechamento", prompt: "Escreva 5 fechamentos de email de vendas com CTA forte para [produto]." },
  { id: 144, category: "copywriting", title: "Assunto de Email - Curiosidade", prompt: "Crie 10 assuntos de email que despertem curiosidade sobre [tema/produto]." },
  { id: 145, category: "copywriting", title: "Assunto de Email - Urgência", prompt: "Escreva 10 assuntos de email que criem urgência para abrir e comprar." },
  { id: 146, category: "copywriting", title: "Assunto de Email - Benefício", prompt: "Crie 10 assuntos de email que destaquem benefícios de [produto/oferta]." },
  { id: 147, category: "copywriting", title: "Assunto de Email - Pessoal", prompt: "Escreva 10 assuntos de email que pareçam pessoais e gerem abertura." },
  { id: 148, category: "copywriting", title: "Assunto de Email - Controvérsia", prompt: "Crie 10 assuntos de email polêmicos (mas respeitosos) sobre [tema]." },
  { id: 149, category: "copywriting", title: "Post de Instagram - Legenda", prompt: "Escreva uma legenda de Instagram de 150 palavras sobre [tema] com CTA." },
  { id: 150, category: "copywriting", title: "Post de Instagram - Hook", prompt: "Crie 10 hooks (ganchos) para primeiros 3 segundos de Reels sobre [tema]." },
  { id: 151, category: "copywriting", title: "Post de Instagram - CTA", prompt: "Escreva 10 CTAs para legendas de Instagram que gerem engajamento." },
  { id: 152, category: "copywriting", title: "Post de Instagram - Hashtags", prompt: "Crie 30 hashtags estratégicas para post sobre [nicho/tema]." },
  { id: 153, category: "copywriting", title: "Post de Instagram - Carrossel", prompt: "Escreva o conteúdo de um carrossel de 10 slides sobre [tema]." },
  { id: 154, category: "copywriting", title: "Script de Reels - Hook", prompt: "Crie 10 hooks para Reels de 30-60 segundos sobre [tema]." },
  { id: 155, category: "copywriting", title: "Script de Reels - Corpo", prompt: "Escreva o corpo de um Reels de 60 segundos sobre [tema/produto]." },
  { id: 156, category: "copywriting", title: "Script de Reels - CTA", prompt: "Crie 10 CTAs finais para Reels que levem ao link na bio." },
  { id: 157, category: "copywriting", title: "Script de TikTok - Hook", prompt: "Escreva 10 hooks para TikTok que prendam nos primeiros 2 segundos." },
  { id: 158, category: "copywriting", title: "Script de TikTok - Storytelling", prompt: "Crie um roteiro de TikTok de 60 segundos contando uma história sobre [tema]." },
  { id: 159, category: "copywriting", title: "Script de TikTok - Tutorial", prompt: "Escreva um roteiro de tutorial para TikTok sobre [tema] em 60 segundos." },
  { id: 160, category: "copywriting", title: "Script de YouTube - Intro", prompt: "Crie 5 introduções de YouTube que prendam nos primeiros 15 segundos." },
  { id: 161, category: "copywriting", title: "Script de YouTube - Conteúdo", prompt: "Escreva a estrutura de um vídeo de YouTube de 10 minutos sobre [tema]." },
  { id: 162, category: "copywriting", title: "Script de YouTube - CTA", prompt: "Crie 5 CTAs para final de vídeo de YouTube que gerem inscrição e clique." },
  { id: 163, category: "copywriting", title: "Título de YouTube", prompt: "Escreva 10 títulos de YouTube sobre [tema] que gerem cliques." },
  { id: 164, category: "copywriting", title: "Descrição de YouTube", prompt: "Crie uma descrição otimizada para vídeo de YouTube sobre [tema]." },
  { id: 165, category: "copywriting", title: "Thumbnail de YouTube - Texto", prompt: "Escreva 10 textos curtos para thumbnail de YouTube sobre [tema]." },
  { id: 166, category: "copywriting", title: "Post de LinkedIn - Profissional", prompt: "Escreva um post de LinkedIn profissional sobre [tema] que gere autoridade." },
  { id: 167, category: "copywriting", title: "Post de LinkedIn - Storytelling", prompt: "Crie um post de LinkedIn contando uma história de superação relacionada a [tema]." },
  { id: 168, category: "copywriting", title: "Post de LinkedIn - Lista", prompt: "Escreva um post de LinkedIn no formato lista sobre [tema]." },
  { id: 169, category: "copywriting", title: "Post de LinkedIn - Pergunta", prompt: "Crie um post de LinkedIn com pergunta que gere debate sobre [tema]." },
  { id: 170, category: "copywriting", title: "Post de LinkedIn - Insight", prompt: "Escreva um post de LinkedIn compartilhando um insight valioso sobre [tema]." },
  { id: 171, category: "copywriting", title: "Bio de Instagram - Pessoal", prompt: "Crie 5 bios de Instagram pessoais que transmitam autoridade em [nicho]." },
  { id: 172, category: "copywriting", title: "Bio de Instagram - Negócios", prompt: "Escreva 5 bios de Instagram para negócios que vendam [produto/serviço]." },
  { id: 173, category: "copywriting", title: "Bio de Instagram - Afiliado", prompt: "Crie 5 bios de Instagram para afiliados que vendam [produto]." },
  { id: 174, category: "copywriting", title: "Bio de Instagram - Criador", prompt: "Escreva 5 bios de Instagram para criadores de conteúdo sobre [nicho]." },
  { id: 175, category: "copywriting", title: "Bio de Instagram - Coach", prompt: "Crie 5 bios de Instagram para coaches/mentores de [nicho]." },
  { id: 176, category: "copywriting", title: "Descrição de Produto - Curta", prompt: "Escreva uma descrição curta (50 palavras) para [produto]." },
  { id: 177, category: "copywriting", title: "Descrição de Produto - Média", prompt: "Crie uma descrição média (150 palavras) para [produto]." },
  { id: 178, category: "copywriting", title: "Descrição de Produto - Longa", prompt: "Escreva uma descrição longa (400 palavras) para [produto]." },
  { id: 179, category: "copywriting", title: "Descrição de Produto - Emocional", prompt: "Crie uma descrição emocional para [produto] que conecte com desejos." },
  { id: 180, category: "copywriting", title: "Descrição de Produto - Lógico", prompt: "Escreva uma descrição lógica/racional para [produto] que justifique a compra." },
  { id: 181, category: "copywriting", title: "Slogan - Curto", prompt: "Crie 10 slogans curtos (3-5 palavras) para [marca/produto]." },
  { id: 182, category: "copywriting", title: "Slogan - Memorável", prompt: "Escreva 10 slogans memoráveis e criativos para [marca/produto]." },
  { id: 183, category: "copywriting", title: "Slogan - Emocional", prompt: "Crie 10 slogans que apelem para emoções para [marca/produto]." },
  { id: 184, category: "copywriting", title: "Slogan - Benefício", prompt: "Escreva 10 slogans que destaquem benefícios para [marca/produto]." },
  { id: 185, category: "copywriting", title: "Slogan - Diferencial", prompt: "Crie 10 slogans que destaquem diferenciais para [marca/produto]." },
  { id: 186, category: "copywriting", title: "Tagline - Marca", prompt: "Escreva 10 taglines para posicionar [marca] no mercado." },
  { id: 187, category: "copywriting", title: "Tagline - Campanha", prompt: "Crie 10 taglines para campanha de [produto/serviço]." },
  { id: 188, category: "copywriting", title: "Tagline - Lançamento", prompt: "Escreva 10 taglines para lançamento de [produto]." },
  { id: 189, category: "copywriting", title: "Tagline - Promoção", prompt: "Crie 10 taglines para promoção/oferta de [produto]." },
  { id: 190, category: "copywriting", title: "Tagline - Institucional", prompt: "Escreva 10 taglines institucionais para [marca/empresa]." },
  { id: 191, category: "copywriting", title: "Parágrafo de Abertura - História", prompt: "Escreva um parágrafo de abertura contando uma história sobre [tema]." },
  { id: 192, category: "copywriting", title: "Parágrafo de Abertura - Estatística", prompt: "Crie um parágrafo de abertura com estatística impactante sobre [tema]." },
  { id: 193, category: "copywriting", title: "Parágrafo de Abertura - Pergunta", prompt: "Escreva um parágrafo de abertura com pergunta provocativa sobre [tema]." },
  { id: 194, category: "copywriting", title: "Parágrafo de Abertura - Afirmação", prompt: "Crie um parágrafo de abertura com afirmação ousada sobre [tema]." },
  { id: 195, category: "copywriting", title: "Parágrafo de Abertura - Cenário", prompt: "Escreva um parágrafo de abertura pintando um cenário sobre [tema]." },
  { id: 196, category: "copywriting", title: "Parágrafo de Fechamento - CTA", prompt: "Crie um parágrafo de fechamento com CTA forte para [produto/oferta]." },
  { id: 197, category: "copywriting", title: "Parágrafo de Fechamento - Resumo", prompt: "Escreva um parágrafo de fechamento resumindo benefícios de [produto]." },
  { id: 198, category: "copywriting", title: "Parágrafo de Fechamento - Urgência", prompt: "Crie um parágrafo de fechamento com urgência para [oferta]." },
  { id: 199, category: "copywriting", title: "Parágrafo de Fechamento - Inspiração", prompt: "Escreva um parágrafo de fechamento inspiracional sobre [tema]." },
  { id: 200, category: "copywriting", title: "Parágrafo de Fechamento - Garantia", prompt: "Crie um parágrafo de fechamento reforçando garantia de [produto]." },

  // INSTAGRAM/SOCIAL MEDIA (100 prompts)
  { id: 201, category: "instagram", title: "Post Educativo", prompt: "Crie um post educativo sobre [tema] que ensine algo valioso em 3 pontos principais." },
  { id: 202, category: "instagram", title: "Post Inspiracional", prompt: "Escreva um post inspiracional sobre [tema] que motive ação imediata." },
  { id: 203, category: "instagram", title: "Post de Bastidores", prompt: "Crie um post mostrando bastidores do seu dia/trabalho com [tema]." },
  { id: 204, category: "instagram", title: "Post de Resultado", prompt: "Escreva um post mostrando resultado/conquista relacionada a [tema/produto]." },
  { id: 205, category: "instagram", title: "Post de Pergunta", prompt: "Crie um post com pergunta que gere muitos comentários sobre [tema]." },
  { id: 206, category: "instagram", title: "Post de Enquete", prompt: "Escreva um post com enquete/poll para stories sobre [tema]." },
  { id: 207, category: "instagram", title: "Post de Mito vs Verdade", prompt: "Crie um post desmistificando [mito] e apresentando a verdade sobre [tema]." },
  { id: 208, category: "instagram", title: "Post de Lista", prompt: "Escreva um post no formato '5 coisas que...' sobre [tema]." },
  { id: 209, category: "instagram", title: "Post de Tutorial", prompt: "Crie um post tutorial passo a passo sobre [tema] em 5 etapas." },
  { id: 210, category: "instagram", title: "Post de Checklist", prompt: "Escreva um post com checklist sobre [tema] que as pessoas possam salvar." },
  { id: 211, category: "instagram", title: "Post de Comparação", prompt: "Crie um post comparando [opção A] vs [opção B] sobre [tema]." },
  { id: 212, category: "instagram", title: "Post de Antes/Depois", prompt: "Escreva um post mostrando transformação antes/depois de [ação/método]." },
  { id: 213, category: "instagram", title: "Post de Depoimento", prompt: "Crie um post destacando depoimento de cliente sobre [produto/serviço]." },
  { id: 214, category: "instagram", title: "Post de Curiosidade", prompt: "Escreva um post com curiosidade surpreendente sobre [tema]." },
  { id: 215, category: "instagram", title: "Post de Dica Rápida", prompt: "Crie um post com dica rápida e acionável sobre [tema]." },
  { id: 216, category: "instagram", title: "Post de Erro Comum", prompt: "Escreva um post sobre erro comum em [tema] e como evitar." },
  { id: 217, category: "instagram", title: "Post de Ferramenta", prompt: "Crie um post recomendando ferramenta/recurso útil para [tema]." },
  { id: 218, category: "instagram", title: "Post de Citação", prompt: "Escreva um post com citação inspiracional relacionada a [tema]." },
  { id: 219, category: "instagram", title: "Post de História Pessoal", prompt: "Crie um post contando história pessoal relacionada a [tema]." },
  { id: 220, category: "instagram", title: "Post de Desafio", prompt: "Escreva um post lançando desafio de 7/30 dias sobre [tema]." },
  { id: 221, category: "instagram", title: "Post de Tendência", prompt: "Crie um post sobre tendência atual em [nicho/tema]." },
  { id: 222, category: "instagram", title: "Post de Opinião", prompt: "Escreva um post com opinião forte/polemica sobre [tema]." },
  { id: 223, category: "instagram", title: "Post de Celebração", prompt: "Crie um post celebrando marco/conquista (1000 seguidores, 1 ano, etc)." },
  { id: 224, category: "instagram", title: "Post de Gratidão", prompt: "Escreva um post de gratidão para seguidores/clientes sobre [tema]." },
  { id: 225, category: "instagram", title: "Post de Anúncio", prompt: "Crie um post anunciando novidade/lançamento de [produto/serviço]." },
  { id: 226, category: "instagram", title: "Post de Promoção", prompt: "Escreva um post anunciando promoção/oferta de [produto/serviço]." },
  { id: 227, category: "instagram", title: "Post de Lançamento", prompt: "Crie um post de lançamento para [produto] com urgência." },
  { id: 228, category: "instagram", title: "Post de Última Chance", prompt: "Escreva um post de última chance para [oferta/produto]." },
  { id: 229, category: "instagram", title: "Post de Contagem Regressiva", prompt: "Crie um post de contagem regressiva para [lançamento/evento]." },
  { id: 230, category: "instagram", title: "Post de Antecipação", prompt: "Escreva um post gerando antecipação para [lançamento/produto]." },
  { id: 231, category: "instagram", title: "Post de Revelação", prompt: "Crie um post revelando [produto/novidade] de forma impactante." },
  { id: 232, category: "instagram", title: "Post de Bastidores - Criação", prompt: "Escreva um post mostrando processo de criação de [produto/conteúdo]." },
  { id: 233, category: "instagram", title: "Post de Bastidores - Dia a Dia", prompt: "Crie um post mostrando um dia típico trabalhando com [tema]." },
  { id: 234, category: "instagram", title: "Post de Bastidores - Equipe", prompt: "Escreva um post apresentando equipe/parceiros de [negócio]." },
  { id: 235, category: "instagram", title: "Post de Bastidores - Ferramentas", prompt: "Crie um post mostrando ferramentas usadas no dia a dia de [tema]." },
  { id: 236, category: "instagram", title: "Post de FAQ", prompt: "Escreva um post respondendo pergunta frequente sobre [tema]." },
  { id: 237, category: "instagram", title: "Post de Mitos", prompt: "Crie um post desmistificando 5 mitos sobre [tema]." },
  { id: 238, category: "instagram", title: "Post de Verdades", prompt: "Escreva um post revelando 5 verdades sobre [tema] que ninguém conta." },
  { id: 239, category: "instagram", title: "Post de Segredos", prompt: "Crie um post revelando 3 segredos sobre [tema] que geram resultados." },
  { id: 240, category: "instagram", title: "Post de Hack", prompt: "Escreva um post com hack/dica avançada sobre [tema]." },
  { id: 241, category: "instagram", title: "Post de Template", prompt: "Crie um post oferecendo template/recurso gratuito sobre [tema]." },
  { id: 242, category: "instagram", title: "Post de Case Study", prompt: "Escreva um post de estudo de caso sobre cliente que teve resultados com [produto]." },
  { id: 243, category: "instagram", title: "Post de Transformação", prompt: "Crie um post mostrando jornada de transformação de [pessoa/empresa]." },
  { id: 244, category: "instagram", title: "Post de Lição Aprendida", prompt: "Escreva um post compartilhando lição aprendida sobre [tema]." },
  { id: 245, category: "instagram", title: "Post de Fracasso", prompt: "Crie um post contando sobre fracasso/erro e o que aprendeu com [tema]." },
  { id: 246, category: "instagram", title: "Post de Sucesso", prompt: "Escreva um post celebrando sucesso/conquista relacionada a [tema]." },
  { id: 247, category: "instagram", title: "Post de Meta", prompt: "Crie um post compartilhando meta/objetivo sobre [tema]." },
  { id: 248, category: "instagram", title: "Post de Reflexão", prompt: "Escreva um post de reflexão/fim de semana sobre [tema]." },
  { id: 249, category: "instagram", title: "Post de Motivação", prompt: "Crie um post motivacional para começar a semana sobre [tema]." },
  { id: 250, category: "instagram", title: "Post de Produtividade", prompt: "Escreva um post com dica de produtividade sobre [tema]." },
  { id: 251, category: "instagram", title: "Post de Mindset", prompt: "Crie um post sobre mindset/mentalidade para [tema]." },
  { id: 252, category: "instagram", title: "Post de Hábito", prompt: "Escreva um post sobre hábito recomendado para [tema]." },
  { id: 253, category: "instagram", title: "Post de Rotina", prompt: "Crie um post compartilhando rotina matinal/noturna sobre [tema]." },
  { id: 254, category: "instagram", title: "Post de Recomendação", prompt: "Escreva um post recomendando livro/podcast/cursos sobre [tema]." },
  { id: 255, category: "instagram", title: "Post de Review", prompt: "Crie um post fazendo review de [produto/ferramenta/livro]." },
  { id: 256, category: "instagram", title: "Post de Unboxing", prompt: "Escreva um post de unboxing/reveal de [produto]." },
  { id: 257, category: "instagram", title: "Post de Tutorial Rápido", prompt: "Crie um post de tutorial rápido (Reels) sobre [tema]." },
  { id: 258, category: "instagram", title: "Post de Hack de IA", prompt: "Escreva um post mostrando como usar IA para [tema]." },
  { id: 259, category: "instagram", title: "Post de Automação", prompt: "Crie um post mostrando automação que economiza tempo em [tema]." },
  { id: 260, category: "instagram", title: "Post de Ferramenta Gratuita", prompt: "Escreva um post recomendando ferramenta gratuita para [tema]." },
  { id: 261, category: "instagram", title: "Post de Ferramenta Paga", prompt: "Crie um post justificando investimento em ferramenta paga para [tema]." },
  { id: 262, category: "instagram", title: "Post de Comparação de Ferramentas", prompt: "Escreva um post comparando ferramentas para [tema]." },
  { id: 263, category: "instagram", title: "Post de Tutorial de Ferramenta", prompt: "Crie um post tutorial de como usar [ferramenta] para [tema]." },
  { id: 264, category: "instagram", title: "Post de Resultado com Ferramenta", prompt: "Escreva um post mostrando resultado obtido com [ferramenta]." },
  { id: 265, category: "instagram", title: "Post de Alternativa", prompt: "Crie um post apresentando alternativa mais barata/acessível para [ferramenta]." },
  { id: 266, category: "instagram", title: "Post de Atualização", prompt: "Escreva um post sobre atualização/novidade de [ferramenta/plataforma]." },
  { id: 267, category: "instagram", title: "Post de Dica de Segurança", prompt: "Crie um post com dica de segurança digital sobre [tema]." },
  { id: 268, category: "instagram", title: "Post de Privacidade", prompt: "Escreva um post sobre privacidade/proteção de dados em [tema]." },
  { id: 269, category: "instagram", title: "Post de Tendência Tecnológica", prompt: "Crie um post sobre tendência tecnológica em [nicho]." },
  { id: 270, category: "instagram", title: "Post de Futuro", prompt: "Escreva um post sobre futuro de [nicho/tema] nos próximos 5 anos." },
  { id: 271, category: "instagram", title: "Post de Oportunidade", prompt: "Crie um post sobre oportunidade em [nicho/tema] para 2025." },
  { id: 272, category: "instagram", title: "Post de Mercado", prompt: "Escreva um post sobre situação atual do mercado de [nicho]." },
  { id: 273, category: "instagram", title: "Post de Estatística", prompt: "Crie um post com estatística impactante sobre [nicho/tema]." },
  { id: 274, category: "instagram", title: "Post de Pesquisa", prompt: "Escreva um post compartilhando resultado de pesquisa sobre [tema]." },
  { id: 275, category: "instagram", title: "Post de Tendência de Consumo", prompt: "Crie um post sobre tendência de consumo em [nicho]." },
  { id: 276, category: "instagram", title: "Post de Comportamento", prompt: "Escreva um post sobre comportamento do consumidor em [nicho]." },
  { id: 277, category: "instagram", title: "Post de Persona", prompt: "Crie um post definindo persona/cliente ideal de [nicho]." },
  { id: 278, category: "instagram", title: "Post de Dor do Cliente", prompt: "Escreva um post identificando dor/problema do cliente em [nicho]." },
  { id: 279, category: "instagram", title: "Post de Solução", prompt: "Crie um post apresentando solução para [dor/problema] em [nicho]." },
  { id: 280, category: "instagram", title: "Post de Benefício", prompt: "Escreva um post destacando benefício principal de [produto/serviço]." },
  { id: 281, category: "instagram", title: "Post de Feature", prompt: "Crie um post destacando feature/funcionalidade de [produto]." },
  { id: 282, category: "instagram", title: "Post de Diferencial", prompt: "Escreva um post destacando diferencial de [produto] vs concorrência." },
  { id: 283, category: "instagram", title: "Post de Garantia", prompt: "Crie um post destacando garantia de [produto] para eliminar objeções." },
  { id: 284, category: "instagram", title: "Post de Suporte", prompt: "Escreva um post destacando suporte/atendimento de [produto/empresa]." },
  { id: 285, category: "instagram", title: "Post de Comunidade", prompt: "Crie um post destacando comunidade de alunos/clientes de [produto]." },
  { id: 286, category: "instagram", title: "Post de Atualização de Produto", prompt: "Escreva um post anunciando atualização de [produto]." },
  { id: 287, category: "instagram", title: "Post de Novo Módulo", prompt: "Crie um post anunciando novo módulo/conteúdo de [produto]." },
  { id: 288, category: "instagram", title: "Post de Bônus", prompt: "Escreva um post anunciando bônus exclusivo de [produto]." },
  { id: 289, category: "instagram", title: "Post de Oferta Especial", prompt: "Crie um post anunciando oferta especial/desconto de [produto]." },
  { id: 290, category: "instagram", title: "Post de Black Friday", prompt: "Escreva um post de Black Friday para [produto/oferta]." },
  { id: 291, category: "instagram", title: "Post de Cyber Monday", prompt: "Crie um post de Cyber Monday para [produto/oferta]." },
  { id: 292, category: "instagram", title: "Post de Natal", prompt: "Escreva um post de Natal/promoção natalina para [produto]." },
  { id: 293, category: "instagram", title: "Post de Ano Novo", prompt: "Crie um post de Ano Novo/metass para [nicho/tema]." },
  { id: 294, category: "instagram", title: "Post de Carnaval", prompt: "Escreva um post de Carnaval relacionado a [nicho/tema]." },
  { id: 295, category: "instagram", title: "Post de Páscoa", prompt: "Crie um post de Páscoa relacionado a [nicho/tema]." },
  { id: 296, category: "instagram", title: "Post de Dia das Mães", prompt: "Escreva um post de Dia das Mães para [produto/serviço]." },
  { id: 297, category: "instagram", title: "Post de Dia dos Namorados", prompt: "Crie um post de Dia dos Namorados para [produto/serviço]." },
  { id: 298, category: "instagram", title: "Post de Dia dos Pais", prompt: "Escreva um post de Dia dos Pais para [produto/serviço]." },
  { id: 299, category: "instagram", title: "Post de Black November", prompt: "Crie um post de Black November para [produto/oferta]." },
  { id: 300, category: "instagram", title: "Post de Fim de Ano", prompt: "Escreva um post de balanço/review de fim de ano sobre [tema]." },

  // VENDAS/AFILIADOS (100 prompts)
  { id: 301, category: "vendas", title: "Primeira Venda como Afiliado", prompt: "Crie um plano de ação de 7 dias para realizar a primeira venda como afiliado de [produto]." },
  { id: 302, category: "vendas", title: "Estratégia de Instagram para Afiliados", prompt: "Desenvolva uma estratégia completa de Instagram para vender [produto] como afiliado." },
  { id: 303, category: "vendas", title: "Estratégia de TikTok para Afiliados", prompt: "Crie uma estratégia de TikTok para vender [produto] como afiliado com conteúdo viral." },
  { id: 304, category: "vendas", title: "Estratégia de YouTube para Afiliados", prompt: "Desenvolva uma estratégia de YouTube para vender [produto] como afiliado com vídeos." },
  { id: 305, category: "vendas", title: "Estratégia de Facebook Ads para Afiliados", prompt: "Crie uma estratégia de Facebook Ads para vender [produto] como afiliado com R$ 20/dia." },
  { id: 306, category: "vendas", title: "Estratégia de Google Ads para Afiliados", prompt: "Desenvolva uma estratégia de Google Ads para vender [produto] como afiliado." },
  { id: 307, category: "vendas", title: "Estratégia de Email Marketing para Afiliados", prompt: "Crie uma estratégia de email marketing para vender [produto] como afiliado." },
  { id: 308, category: "vendas", title: "Estratégia de WhatsApp para Afiliados", prompt: "Desenvolva uma estratégia de WhatsApp para vender [produto] como afiliado." },
  { id: 309, category: "vendas", title: "Estratégia de Telegram para Afiliados", prompt: "Crie uma estratégia de Telegram para vender [produto] como afiliado." },
  { id: 310, category: "vendas", title: "Estratégia de Pinterest para Afiliados", prompt: "Desenvolva uma estratégia de Pinterest para vender [produto] como afiliado." },
  { id: 311, category: "vendas", title: "Como Escolher Produto para Vender", prompt: "Crie um guia de como escolher o produto certo para vender como afiliado em [nicho]." },
  { id: 312, category: "vendas", title: "Como Criar Conteúdo que Vende", prompt: "Desenvolva um framework para criar conteúdo que vende [produto] sem parecer vendedor." },
  { id: 313, category: "vendas", title: "Como Criar Funil de Vendas", prompt: "Crie um funil de vendas simples para vender [produto] como afiliado." },
  { id: 314, category: "vendas", title: "Como Criar Página de Captura", prompt: "Desenvolva uma estrutura de página de captura para vender [produto] como afiliado." },
  { id: 315, category: "vendas", title: "Como Criar Isca Digital", prompt: "Crie ideias de isca digital (ebook, aula gratuita) para atrair leads de [nicho]." },
  { id: 316, category: "vendas", title: "Como Fazer Review de Produto", prompt: "Escreva um roteiro de review honesto sobre [produto] que convença a comprar." },
  { id: 317, category: "vendas", title: "Como Fazer Comparação de Produtos", prompt: "Crie um roteiro de comparação entre [produto A] e [produto B] que venda [produto A]." },
  { id: 318, category: "vendas", title: "Como Criar Tutorial que Vende", prompt: "Desenvolva um roteiro de tutorial sobre [tema] que naturalmente leve a [produto]." },
  { id: 319, category: "vendas", title: "Como Criar Depoimento Falso (Ético)", prompt: "Escreva um roteiro de depoimento baseado em resultados reais de [produto] que seja ético." },
  { id: 320, category: "vendas", title: "Como Usar Prova Social", prompt: "Crie uma estratégia para usar prova social (prints, depoimentos) para vender [produto]." },
  { id: 321, category: "vendas", title: "Como Criar Urgência", prompt: "Desenvolva uma estratégia para criar urgência legítima ao vender [produto]." },
  { id: 322, category: "vendas", title: "Como Criar Escassez", prompt: "Crie uma estratégia para criar escassez legítima ao vender [produto]." },
  { id: 323, category: "vendas", title: "Como Lidar com Objeções", prompt: "Escreva respostas para as 10 objeções mais comuns ao vender [produto]." },
  { id: 324, category: "vendas", title: "Como Fazer Follow-up", prompt: "Crie uma sequência de follow-up (5 mensagens) para leads que não compraram [produto]." },
  { id: 325, category: "vendas", title: "Como Recuperar Carrinho Abandonado", prompt: "Desenvolva uma estratégia de recuperação de carrinho abandonado para [produto]." },
  { id: 326, category: "vendas", title: "Como Fazer Upsell", prompt: "Crie uma estratégia de upsell para aumentar ticket médio ao vender [produto]." },
  { id: 327, category: "vendas", title: "Como Fazer Cross-sell", prompt: "Desenvolva uma estratégia de cross-sell para vender [produto complementar] junto com [produto principal]." },
  { id: 328, category: "vendas", title: "Como Criar Oferta Irresistível", prompt: "Crie uma oferta irresistível para [produto] com bônus, garantia e escassez." },
  { id: 329, category: "vendas", title: "Como Ancorar Preço", prompt: "Escreva uma estratégia de ancoragem de preço para justificar o valor de [produto]." },
  { id: 330, category: "vendas", title: "Como Criar Bônus", prompt: "Desenvolva 5 ideias de bônus para agregar valor a [produto]." },
  { id: 331, category: "vendas", title: "Como Criar Garantia", prompt: "Escreva uma garantia poderosa para [produto] que elimine riscos." },
  { id: 332, category: "vendas", title: "Como Criar Landing Page", prompt: "Crie uma estrutura de landing page para vender [produto] com alta conversão." },
  { id: 333, category: "vendas", title: "Como Criar Sales Page", prompt: "Desenvolva uma estrutura de sales page (página de vendas) para [produto]." },
  { id: 334, category: "vendas", title: "Como Criar Checkout", prompt: "Escreva uma estratégia de checkout otimizado para reduzir abandono em [produto]." },
  { id: 335, category: "vendas", title: "Como Criar Order Bump", prompt: "Crie uma oferta de order bump para aumentar ticket médio de [produto]." },
  { id: 336, category: "vendas", title: "Como Criar Thank You Page", prompt: "Desenvolva uma thank you page (página de obrigado) para [produto] que gere upsell." },
  { id: 337, category: "vendas", title: "Como Criar Sequência de Emails de Vendas", prompt: "Escreva uma sequência de 7 emails de vendas para [produto]." },
  { id: 338, category: "vendas", title: "Como Criar Sequência de Stories de Vendas", prompt: "Crie uma sequência de 10 stories vendendo [produto] com gatilhos mentais." },
  { id: 339, category: "vendas", title: "Como Criar Sequência de Reels de Vendas", prompt: "Desenvolva uma sequência de 5 Reels vendendo [produto]." },
  { id: 340, category: "vendas", title: "Como Criar Sequência de TikToks de Vendas", prompt: "Escreva uma sequência de 5 TikToks vendendo [produto]." },
  { id: 341, category: "vendas", title: "Como Criar Sequência de Vídeos de YouTube", prompt: "Crie uma sequência de 3 vídeos de YouTube vendendo [produto]." },
  { id: 342, category: "vendas", title: "Como Criar Sequência de Posts de Vendas", prompt: "Desenvolva uma sequência de 10 posts vendendo [produto]." },
  { id: 343, category: "vendas", title: "Como Criar Sequência de Mensagens de WhatsApp", prompt: "Escreva uma sequência de 5 mensagens de WhatsApp vendendo [produto]." },
  { id: 344, category: "vendas", title: "Como Criar Sequência de Mensagens de Telegram", prompt: "Crie uma sequência de 5 mensagens de Telegram vendendo [produto]." },
  { id: 345, category: "vendas", title: "Como Criar Campanha de Lançamento", prompt: "Desenvolva uma campanha de lançamento de 7 dias para [produto]." },
  { id: 346, category: "vendas", title: "Como Criar Campanha de Black Friday", prompt: "Escreva uma campanha de Black Friday para [produto]." },
  { id: 347, category: "vendas", title: "Como Criar Campanha de Natal", prompt: "Crie uma campanha de Natal para [produto]." },
  { id: 348, category: "vendas", title: "Como Criar Campanha de Ano Novo", prompt: "Desenvolva uma campanha de Ano Novo para [produto]." },
  { id: 349, category: "vendas", title: "Como Criar Campanha de Volta às Aulas", prompt: "Escreva uma campanha de Volta às Aulas para [produto]." },
  { id: 350, category: "vendas", title: "Como Criar Campanha de Dia das Mães", prompt: "Crie uma campanha de Dia das Mães para [produto]." },
  { id: 351, category: "vendas", title: "Como Criar Campanha de Dia dos Namorados", prompt: "Desenvolva uma campanha de Dia dos Namorados para [produto]." },
  { id: 352, category: "vendas", title: "Como Criar Campanha de Dia dos Pais", prompt: "Escreva uma campanha de Dia dos Pais para [produto]." },
  { id: 353, category: "vendas", title: "Como Criar Campanha Sazonal", prompt: "Crie uma campanha sazonal para [produto] em [época do ano]." },
  { id: 354, category: "vendas", title: "Como Criar Campanha de Remarketing", prompt: "Desenvolva uma campanha de remarketing para recuperar vendas perdidas de [produto]." },
  { id: 355, category: "vendas", title: "Como Criar Campanha de Upsell", prompt: "Escreva uma campanha de upsell para vender [produto complementar] para clientes de [produto principal]." },
  { id: 356, category: "vendas", title: "Como Criar Campanha de Cross-sell", prompt: "Crie uma campanha de cross-sell para vender [produto complementar] junto com [produto principal]." },
  { id: 357, category: "vendas", title: "Como Criar Campanha de Indicação", prompt: "Desenvolva uma campanha de indicação para [produto] com recompensas." },
  { id: 358, category: "vendas", title: "Como Criar Campanha de Afiliados", prompt: "Escreva uma campanha de afiliados para recrutar novos afiliados para [produto]." },
  { id: 359, category: "vendas", title: "Como Criar Campanha de Influenciadores", prompt: "Crie uma campanha de influenciadores para promover [produto]." },
  { id: 360, category: "vendas", title: "Como Criar Campanha de Parcerias", prompt: "Desenvolva uma campanha de parcerias para promover [produto]." },
  { id: 361, category: "vendas", title: "Como Criar Campanha de Eventos", prompt: "Escreva uma campanha de eventos (webinar, live) para vender [produto]." },
  { id: 362, category: "vendas", title: "Como Criar Campanha de Desafio", prompt: "Crie uma campanha de desafio (7 dias, 30 dias) para [nicho/produto]." },
  { id: 363, category: "vendas", title: "Como Criar Campanha de Mentoria", prompt: "Desenvolva uma campanha de mentoria para [nicho]." },
  { id: 364, category: "vendas", title: "Como Criar Campanha de Consultoria", prompt: "Escreva uma campanha de consultoria para [nicho]." },
  { id: 365, category: "vendas", title: "Como Criar Campanha de Curso", prompt: "Crie uma campanha de curso para [nicho/tema]." },
  { id: 366, category: "vendas", title: "Como Criar Campanha de Ebook", prompt: "Desenvolva uma campanha de ebook para [nicho/tema]." },
  { id: 367, category: "vendas", title: "Como Criar Campanha de Webinar", prompt: "Escreva uma campanha de webinar para vender [produto]." },
  { id: 368, category: "vendas", title: "Como Criar Campanha de Masterclass", prompt: "Crie uma campanha de masterclass para vender [produto]." },
  { id: 369, category: "vendas", title: "Como Criar Campanha de Workshop", prompt: "Desenvolva uma campanha de workshop para vender [produto]." },
  { id: 370, category: "vendas", title: "Como Criar Campanha de Imersão", prompt: "Escreva uma campanha de imersão para vender [produto]." },
  { id: 371, category: "vendas", title: "Como Criar Campanha de Comunidade", prompt: "Crie uma campanha de comunidade/membership para [nicho]." },
  { id: 372, category: "vendas", title: "Como Criar Campanha de Grupo VIP", prompt: "Desenvolva uma campanha de grupo VIP para [nicho]." },
  { id: 373, category: "vendas", title: "Como Criar Campanha de Mastermind", prompt: "Escreva uma campanha de mastermind para [nicho]." },
  { id: 374, category: "vendas", title: "Como Criar Campanha de High Ticket", prompt: "Crie uma campanha para vender produto high ticket (acima de R$ 5000) para [nicho]." },
  { id: 375, category: "vendas", title: "Como Criar Campanha de Low Ticket", prompt: "Desenvolva uma campanha para vender produto low ticket (abaixo de R$ 100) para [nicho]." },
  { id: 376, category: "vendas", title: "Como Criar Campanha de Mid Ticket", prompt: "Escreva uma campanha para vender produto mid ticket (R$ 100-500) para [nicho]." },
  { id: 377, category: "vendas", title: "Como Criar Campanha de Recorrência", prompt: "Crie uma campanha para vender produto de recorrência/assinatura para [nicho]." },
  { id: 378, category: "vendas", title: "Como Criar Campanha de One-time", prompt: "Desenvolva uma campanha para vender produto one-time (pagamento único) para [nicho]." },
  { id: 379, category: "vendas", title: "Como Criar Campanha de Bundle", prompt: "Escreva uma campanha para vender bundle (pacote) de produtos para [nicho]." },
  { id: 380, category: "vendas", title: "Como Criar Campanha de Trial", prompt: "Crie uma campanha para oferecer trial/teste gratuito de [produto]." },
  { id: 381, category: "vendas", title: "Como Criar Campanha de Freemium", prompt: "Desenvolva uma campanha de modelo freemium para [produto]." },
  { id: 382, category: "vendas", title: "Como Criar Campanha de Pay-per-use", prompt: "Escreva uma campanha de modelo pay-per-use para [produto]." },
  { id: 383, category: "vendas", title: "Como Criar Campanha de Pay-what-you-want", prompt: "Crie uma campanha de modelo 'pague o que quiser' para [produto]." },
  { id: 384, category: "vendas", title: "Como Criar Campanha de Crowdfunding", prompt: "Desenvolva uma campanha de crowdfunding para [produto/projeto]." },
  { id: 385, category: "vendas", title: "Como Criar Campanha de Pré-venda", prompt: "Escreva uma campanha de pré-venda para [produto]." },
  { id: 386, category: "vendas", title: "Como Criar Campanha de Lista de Espera", prompt: "Crie uma campanha de lista de espera para [produto]." },
  { id: 387, category: "vendas", title: "Como Criar Campanha de Beta", prompt: "Desenvolva uma campanha de versão beta para [produto]." },
  { id: 388, category: "vendas", title: "Como Criar Campanha de Early Bird", prompt: "Escreva uma campanha de early bird (desconto para primeiros compradores) para [produto]." },
  { id: 389, category: "vendas", title: "Como Criar Campanha de Founders", prompt: "Crie uma campanha de 'founders' (preço especial para primeiros membros) para [produto]." },
  { id: 390, category: "vendas", title: "Como Criar Campanha de Lifetime", prompt: "Desenvolva uma campanha de acesso vitalício para [produto]." },
  { id: 391, category: "vendas", title: "Como Criar Campanha de Afiliado Super", prompt: "Escreva uma campanha para recrutar afiliados super (que vendem muito) para [produto]." },
  { id: 392, category: "vendas", title: "Como Criar Campanha de Co-produção", prompt: "Crie uma campanha de co-produção com outro expert para [produto]." },
  { id: 393, category: "vendas", title: "Como Criar Campanha de Joint Venture", prompt: "Desenvolva uma campanha de joint venture para lançar [produto]." },
  { id: 394, category: "vendas", title: "Como Criar Campanha de Licensing", prompt: "Escreva uma campanha de licensing (licenciamento) para [produto]." },
  { id: 395, category: "vendas", title: "Como Criar Campanha de White Label", prompt: "Crie uma campanha de white label para [produto]." },
  { id: 396, category: "vendas", title: "Como Criar Campanha de Resell", prompt: "Desenvolva uma campanha de revenda para [produto]." },
  { id: 397, category: "vendas", title: "Como Criar Campanha de Dropshipping", prompt: "Escreva uma campanha de dropshipping para [produto/nicho]." },
  { id: 398, category: "vendas", title: "Como Criar Campanha de Print-on-demand", prompt: "Crie uma campanha de print-on-demand para [produto/nicho]." },
  { id: 399, category: "vendas", title: "Como Criar Campanha de Amazon FBA", prompt: "Desenvolva uma campanha de Amazon FBA para [produto/nicho]." },
  { id: 400, category: "vendas", title: "Como Criar Campanha de Marketplace", prompt: "Escreva uma campanha para vender em marketplace (Mercado Livre, Shopee) para [produto]." },

  // IA/CHATGPT (100 prompts)
  { id: 401, category: "ia", title: "Prompt para Criar Headlines", prompt: "Crie 10 headlines persuasivas para [produto/serviço] usando gatilhos mentais de [urgência/curiosidade/autoridade]." },
  { id: 402, category: "ia", title: "Prompt para Criar Copies", prompt: "Escreva uma copy completa de vendas para [produto] usando a fórmula PAS (Problema, Agitação, Solução)." },
  { id: 403, category: "ia", title: "Prompt para Criar Posts", prompt: "Crie 5 posts para Instagram sobre [tema] que gerem engajamento e levem ao link na bio." },
  { id: 404, category: "ia", title: "Prompt para Criar Emails", prompt: "Escreva uma sequência de 5 emails de vendas para [produto] seguindo a jornada do cliente." },
  { id: 405, category: "ia", title: "Prompt para Criar Scripts", prompt: "Crie um roteiro de vídeo de 60 segundos para Reels/TikTok sobre [tema] com hook, corpo e CTA." },
  { id: 406, category: "ia", title: "Prompt para Criar Artigos", prompt: "Escreva um artigo de blog de 1000 palavras sobre [tema] otimizado para SEO com [palavra-chave]." },
  { id: 407, category: "ia", title: "Prompt para Criar Ebooks", prompt: "Crie a estrutura completa de um ebook sobre [tema] com 10 capítulos e introdução." },
  { id: 408, category: "ia", title: "Prompt para Criar Cursos", prompt: "Desenvolva a estrutura de um curso online sobre [tema] com 5 módulos e 10 aulas cada." },
  { id: 409, category: "ia", title: "Prompt para Criar Webinars", prompt: "Escreva um roteiro completo de webinar de 60 minutos sobre [tema] com venda no final." },
  { id: 410, category: "ia", title: "Prompt para Criar Landing Pages", prompt: "Crie a copy completa de uma landing page para [produto] com headline, benefícios, prova social e CTA." },
  { id: 411, category: "ia", title: "Prompt para Criar Anúncios", prompt: "Escreva 5 variações de anúncio para Facebook/Instagram sobre [produto] com diferentes ângulos." },
  { id: 412, category: "ia", title: "Prompt para Criar Bios", prompt: "Crie 5 bios de Instagram para [nicho/profissão] que transmitam autoridade e vendam [produto]." },
  { id: 413, category: "ia", title: "Prompt para Criar Legendas", prompt: "Escreva 10 legendas para posts de Instagram sobre [tema] com CTA no final." },
  { id: 414, category: "ia", title: "Prompt para Criar Hashtags", prompt: "Crie 30 hashtags estratégicas para post sobre [nicho/tema] divididas em populares, médias e nicho." },
  { id: 415, category: "ia", title: "Prompt para Criar CTAs", prompt: "Escreva 15 CTAs (Call to Action) para [produto/oferta] divididos em urgentes, curiosos e diretos." },
  { id: 416, category: "ia", title: "Prompt para Criar Gatilhos", prompt: "Crie 10 parágrafos usando gatilhos mentais (escassez, urgência, prova social) para vender [produto]." },
  { id: 417, category: "ia", title: "Prompt para Criar Objeções", prompt: "Escreva respostas para as 10 objeções mais comuns ao vender [produto]." },
  { id: 418, category: "ia", title: "Prompt para Criar Depoimentos", prompt: "Crie 5 depoimentos fictícios (baseados em resultados reais) para [produto] que pareçam autênticos." },
  { id: 419, category: "ia", title: "Prompt para Criar Stories", prompt: "Escreva uma sequência de 10 stories vendendo [produto] com gatilhos mentais e CTA." },
  { id: 420, category: "ia", title: "Prompt para Criar Reels", prompt: "Crie 5 roteiros de Reels de 30-60 segundos sobre [tema] com hooks virais." },
  { id: 421, category: "ia", title: "Prompt para Criar TikToks", prompt: "Escreva 5 roteiros de TikTok sobre [tema] que tenham potencial viral." },
  { id: 422, category: "ia", title: "Prompt para Criar YouTube", prompt: "Crie um roteiro de vídeo de YouTube de 10 minutos sobre [tema] com intro, conteúdo e CTA." },
  { id: 423, category: "ia", title: "Prompt para Criar Podcasts", prompt: "Desenvolva a estrutura de um episódio de podcast sobre [tema] com introdução, tópicos e encerramento." },
  { id: 424, category: "ia", title: "Prompt para Criar Lives", prompt: "Escreva um roteiro de live de 60 minutos sobre [tema] com interação e venda no final." },
  { id: 425, category: "ia", title: "Prompt para Criar Carrosséis", prompt: "Crie o conteúdo de um carrossel de 10 slides sobre [tema] com hook, conteúdo e CTA." },
  { id: 426, category: "ia", title: "Prompt para Criar Infográficos", prompt: "Escreva o conteúdo de um infográfico sobre [tema] com 7 pontos visuais." },
  { id: 427, category: "ia", title: "Prompt para Criar Checklists", prompt: "Crie um checklist de 20 itens sobre [tema] que as pessoas possam salvar." },
  { id: 428, category: "ia", title: "Prompt para Criar Templates", prompt: "Desenvolva 5 templates editáveis sobre [tema] que as pessoas possam usar." },
  { id: 429, category: "ia", title: "Prompt para Criar Planilhas", prompt: "Crie a estrutura de uma planilha de [tema] com colunas e fórmulas úteis." },
  { id: 430, category: "ia", title: "Prompt para Criar Apresentações", prompt: "Escreva o conteúdo de uma apresentação de 10 slides sobre [tema]." },
  { id: 431, category: "ia", title: "Prompt para Criar Propostas", prompt: "Crie uma estrutura de proposta comercial para [serviço] com seções persuasivas." },
  { id: 432, category: "ia", title: "Prompt para Criar Contratos", prompt: "Escreva uma estrutura de contrato para [serviço] com cláusulas essenciais." },
  { id: 433, category: "ia", title: "Prompt para Criar Faturas", prompt: "Crie um template de fatura/recibo para [serviço] profissional." },
  { id: 434, category: "ia", title: "Prompt para Criar Relatórios", prompt: "Desenvolva uma estrutura de relatório sobre [tema] com seções e métricas." },
  { id: 435, category: "ia", title: "Prompt para Criar Dashboards", prompt: "Escreva a estrutura de um dashboard de [tema] com KPIs e visualizações." },
  { id: 436, category: "ia", title: "Prompt para Criar Planos de Negócio", prompt: "Crie uma estrutura de plano de negócio para [ideia/empresa] com seções essenciais." },
  { id: 437, category: "ia", title: "Prompt para Criar Planos de Marketing", prompt: "Desenvolva um plano de marketing de 90 dias para [empresa/produto]." },
  { id: 438, category: "ia", title: "Prompt para Criar Planos de Conteúdo", prompt: "Escreva um calendário de conteúdo de 30 dias para [plataforma] sobre [nicho]." },
  { id: 439, category: "ia", title: "Prompt para Criar Planos de Mídia", prompt: "Crie um plano de mídia para [empresa] com canais, orçamento e métricas." },
  { id: 440, category: "ia", title: "Prompt para Criar Planos de Vendas", prompt: "Desenvolva um plano de vendas de 90 dias para [produto/serviço]." },
  { id: 441, category: "ia", title: "Prompt para Criar Estratégias", prompt: "Escreva uma estratégia completa de [marketing/vendas/conteúdo] para [empresa/produto]." },
  { id: 442, category: "ia", title: "Prompt para Criar Funis", prompt: "Crie um funil de vendas completo para [produto] com etapas de atração, captura e conversão." },
  { id: 443, category: "ia", title: "Prompt para Criar Jornada do Cliente", prompt: "Desenvolva a jornada do cliente para [produto] com touchpoints e ações em cada etapa." },
  { id: 444, category: "ia", title: "Prompt para Criar Personas", prompt: "Escreva 3 personas detalhadas para [nicho/empresa] com dores, desejos e comportamentos." },
  { id: 445, category: "ia", title: "Prompt para Criar Mapas de Empatia", prompt: "Crie um mapa de empatia para [persona] com o que pensa, sente, vê e faz." },
  { id: 446, category: "ia", title: "Prompt para Criar SWOT", prompt: "Desenvolva uma análise SWOT para [empresa/produto] com forças, fraquezas, oportunidades e ameaças." },
  { id: 447, category: "ia", title: "Prompt para Criar 5 Forças de Porter", prompt: "Escreva uma análise das 5 Forças de Porter para [mercado/nicho]." },
  { id: 448, category: "ia", title: "Prompt para Criar Análise de Concorrência", prompt: "Crie uma análise de concorrência para [empresa] comparando com 3 concorrentes." },
  { id: 449, category: "ia", title: "Prompt para Criar Análise de Mercado", prompt: "Desenvolva uma análise de mercado para [nicho/segmento] com tendências e oportunidades." },
  { id: 450, category: "ia", title: "Prompt para Criar Pesquisa de Mercado", prompt: "Escreva um questionário de pesquisa de mercado sobre [tema] com 20 perguntas." },
  { id: 451, category: "ia", title: "Prompt para Criar Feedback", prompt: "Crie um formulário de feedback para clientes de [produto/serviço] com 15 perguntas." },
  { id: 452, category: "ia", title: "Prompt para Criar NPS", prompt: "Desenvolva uma pesquisa NPS (Net Promoter Score) para [empresa/produto] com perguntas complementares." },
  { id: 453, category: "ia", title: "Prompt para Criar CSAT", prompt: "Escreva uma pesquisa CSAT (Customer Satisfaction) para [produto/serviço]." },
  { id: 454, category: "ia", title: "Prompt para Criar CES", prompt: "Crie uma pesquisa CES (Customer Effort Score) para [produto/serviço]." },
  { id: 455, category: "ia", title: "Prompt para Criar Métricas", prompt: "Desenvolva um dashboard de métricas para [área] com KPIs e fórmulas de cálculo." },
  { id: 456, category: "ia", title: "Prompt para Criar OKRs", prompt: "Escreva OKRs (Objectives and Key Results) para [empresa/equipe] no próximo trimestre." },
  { id: 457, category: "ia", title: "Prompt para Criar KPIs", prompt: "Crie uma lista de KPIs para [área/departamento] com metas e frequência de medição." },
  { id: 458, category: "ia", title: "Prompt para Criar Dashboards de Vendas", prompt: "Desenvolva um dashboard de vendas para [empresa] com métricas de funil e conversão." },
  { id: 459, category: "ia", title: "Prompt para Criar Dashboards de Marketing", prompt: "Escreva um dashboard de marketing para [empresa] com métricas de campanhas e ROI." },
  { id: 460, category: "ia", title: "Prompt para Criar Dashboards de Conteúdo", prompt: "Crie um dashboard de conteúdo para [empresa] com métricas de engajamento e conversão." },
  { id: 461, category: "ia", title: "Prompt para Criar Automações", prompt: "Desenvolva uma automação de marketing para [empresa] com gatilhos, ações e fluxos." },
  { id: 462, category: "ia", title: "Prompt para Criar Workflows", prompt: "Escreva um workflow de vendas para [empresa] com etapas, responsáveis e prazos." },
  { id: 463, category: "ia", title: "Prompt para Criar Processos", prompt: "Crie um processo operacional para [atividade] com etapas, ferramentas e métricas." },
  { id: 464, category: "ia", title: "Prompt para Criar SOPs", prompt: "Desenvolva um SOP (Standard Operating Procedure) para [atividade] com passo a passo detalhado." },
  { id: 465, category: "ia", title: "Prompt para Criar Manuais", prompt: "Escreva um manual de [procedimento/ferramenta] para [empresa/equipe]." },
  { id: 466, category: "ia", title: "Prompt para Criar Tutoriais", prompt: "Crie um tutorial passo a passo sobre [tema/ferramenta] com 10 etapas." },
  { id: 467, category: "ia", title: "Prompt para Criar Guias", prompt: "Desenvolva um guia completo sobre [tema] com introdução, desenvolvimento e conclusão." },
  { id: 468, category: "ia", title: "Prompt para Criar FAQs", prompt: "Escreva 20 perguntas frequentes com respostas sobre [tema/produto]." },
  { id: 469, category: "ia", title: "Prompt para Criar Glossários", prompt: "Crie um glossário com 30 termos técnicos sobre [nicho/tema] e suas definições." },
  { id: 470, category: "ia", title: "Prompt para Criar Dicionários", prompt: "Desenvolva um dicionário de [nicho] com 50 termos e explicações simples." },
  { id: 471, category: "ia", title: "Prompt para Criar Listas", prompt: "Escreva uma lista de 'Top 50 [itens] sobre [tema]' com descrições curtas." },
  { id: 472, category: "ia", title: "Prompt para Criar Rankings", prompt: "Crie um ranking de 'Top 10 [itens] de [ano]' sobre [tema] com justificativas." },
  { id: 473, category: "ia", title: "Prompt para Criar Reviews", prompt: "Escreva um review detalhado de [produto/ferramenta] com prós, contras e veredito." },
  { id: 474, category: "ia", title: "Prompt para Criar Comparativos", prompt: "Desenvolva um comparativo entre [opção A] e [opção B] sobre [tema] com tabela." },
  { id: 475, category: "ia", title: "Prompt para Criar Análises", prompt: "Escreva uma análise detalhada de [tema/situação] com dados, insights e recomendações." },
  { id: 476, category: "ia", title: "Prompt para Criar Resumos", prompt: "Crie um resumo executivo de [livro/artigo/conceito] em 500 palavras." },
  { id: 477, category: "ia", title: "Prompt para Criar Sínteses", prompt: "Desenvolva uma síntese de [tema complexo] em 3 parágrafos simples." },
  { id: 478, category: "ia", title: "Prompt para Criar Explicações", prompt: "Escreva uma explicação de [conceito complexo] para leigos em 300 palavras." },
  { id: 479, category: "ia", title: "Prompt para Criar Traduç", prompt: "Traduza e adapte culturalmente [texto] do [idioma origem] para o português brasileiro." },
  { id: 480, category: "ia", title: "Prompt para Criar Reescritas", prompt: "Reescreva [texto] em tom [formal/informal/persuasivo] mantendo a mensagem original." },
  { id: 481, category: "ia", title: "Prompt para Criar Correções", prompt: "Corrija gramática, ortografia e estilo de [texto] mantendo o tom original." },
  { id: 482, category: "ia", title: "Prompt para Criar Melhorias", prompt: "Melhore [texto] tornando-o mais claro, conciso e persuasivo." },
  { id: 483, category: "ia", title: "Prompt para Criar Expansões", prompt: "Expanda [texto curto] em um artigo completo de 1000 palavras sobre [tema]." },
  { id: 484, category: "ia", title: "Prompt para Criar Condensações", prompt: "Condense [texto longo] em um resumo de 200 palavras mantendo os pontos principais." },
  { id: 485, category: "ia", title: "Prompt para Criar Adaptações", prompt: "Adapte [texto] para [público-alvo] usando linguagem e exemplos apropriados." },
  { id: 486, category: "ia", title: "Prompt para Criar Localizações", prompt: "Localize [texto/conteúdo] para o mercado brasileiro adaptando referências culturais." },
  { id: 487, category: "ia", title: "Prompt para Criar Personalizações", prompt: "Personalize [mensagem/template] para [cliente/segmento] com dados específicos." },
  { id: 488, category: "ia", title: "Prompt para Criar Segmentações", prompt: "Crie 5 variações de [mensagem] para diferentes segmentos de [público-alvo]." },
  { id: 489, category: "ia", title: "Prompt para Criar Testes A/B", prompt: "Desenvolva 2 variações (A e B) de [elemento] para teste A/B com hipóteses." },
  { id: 490, category: "ia", title: "Prompt para Criar Otimizações", prompt: "Otimize [texto/conteúdo] para [objetivo: SEO/conversão/engajamento]." },
  { id: 491, category: "ia", title: "Prompt para Criar Análises de Dados", prompt: "Analise [dados/métricas] e forneça insights acionáveis para [objetivo]." },
  { id: 492, category: "ia", title: "Prompt para Criar Previsões", prompt: "Faça previsões para [mercado/tendência] nos próximos [período] baseadas em [dados]." },
  { id: 493, category: "ia", title: "Prompt para Criar Recomendações", prompt: "Forneça 10 recomendações estratégicas para [empresa/projeto] baseado em [contexto]." },
  { id: 494, category: "ia", title: "Prompt para Criar Soluções", prompt: "Proponha 5 soluções criativas para [problema/desafio] considerando [restrições]." },
  { id: 495, category: "ia", title: "Prompt para Criar Ideias", prompt: "Gere 20 ideias criativas para [objetivo/projeto] pensando fora da caixa." },
  { id: 496, category: "ia", title: "Prompt para Criar Brainstorms", prompt: "Faça um brainstorm estruturado sobre [tema] com ideias organizadas por categorias." },
  { id: 497, category: "ia", title: "Prompt para Criar Mindmaps", prompt: "Crie um mindmap textual sobre [tema] com tópicos principais e sub-tópicos." },
  { id: 498, category: "ia", title: "Prompt para Criar Fluxogramas", prompt: "Desenvolva um fluxograma textual de [processo] com decisões e caminhos." },
  { id: 499, category: "ia", title: "Prompt para Criar Timelines", prompt: "Escreva uma timeline de [projeto/evento] com marcos, datas e entregas." },
  { id: 500, category: "ia", title: "Prompt para Criar Roadmaps", prompt: "Crie um roadmap de [produto/projeto] para os próximos 12 meses com fases e objetivos." }
];
